In [13]:
#ways to run python
#online interpreter # one by one line print in python
#cmd way
#python is a case sensitive language
#cmd only save
#exit() closes the python
#first go to the location and open in notepad and closes with cltrl +s 
#touch f1.py creates a file in linux
#in cmd python command (python f1.py) it executes in cmd
#intellicene nahi hoti yani p jitne functions atey hai
#visul studio 4 
#code . #isai sari visual studio ki files ajaye gi #is kai andar intellicence mujood hoti hai
#magic function %load
#the smarter way to learn python is used in the class

In [2]:
string="faisal"
x=string.title()
print(x)

Faisal


In [3]:
print("hello world")

hello world


In [18]:
class Car():
    def __init__(self,radius):
        self.radius=radius

    def circle(self):
        area=3.14*(self.radius**2)
        return area
    def main1(self):# why do we use self in oop
        print("hello")
obj_1=Car(2)
x=obj_1.circle()
y=obj_1.main1()
#print(obj_1.circle())
print(x)

hello
12.56


In [20]:
tuple_1=(1,2,3,4)
print(tuple_1)

(1, 2, 3, 4)


In [21]:
#magic function %load.py 

In [ ]:
# %load f1.py
print("faisal")
print("saleem")
print("0331-2812064")
print("42201-3297454-9")


In [27]:
#how to check intellicence in jupyter notebook
#pre defined functions for any language
#functions kisi bhi repetion ko rokne kai lie use kartey hai
#programming language sai baney hue pehly sai functions pre- defined functions
# argument jismie koi variable passs nahi kartey hai
# hamein check karne hai kai hamare function 
#shift tab sai pata chalta hai kai konsa konsa argument pass karney hai
#keyword argument sep='' is a key word argument

In [28]:
print('faisal','saleem','0331-2812064')

faisal saleem 0331-2812064


In [30]:
print('faisal','saleem','0331-2812064', sep=' \n') #separator sab kai darmian ab \n new line arahi hai

faisal 
saleem 
0331-2812064


In [32]:
print('faisal','saleem','0331-2812064', sep='*')#shru waley sai pehly nahi ayega or akhri mei nahi ayega beech mei ayega seperator

faisal*saleem*0331-2812064


In [34]:
print('faisal')# by default line \n pai end hoti hai
print('saleem')
print('ok')

faisal
saleem
ok


In [36]:
print('faisal',end='@')# by default line \n pai end hoti hai
print('saleem',end='@')
print('ok',end='@')# ab usei har line par print nahi horaha by default \n ka end khatam kardia

faisal@saleem@ok@

In [39]:
print("faisal's") # agar '  chie ho

faisal's


In [ ]:
print(" '[]'faisal")

In [ ]:
print('faisal','saleem' ,sep=' ') # by default sepearator yaha tab hai usko khatam karney kailie hai

# Data Type

In [1]:
a='Qasim'
type(a)

str

In [2]:
#jupyter notebook last line return karta hai

In [3]:
#list ek sai ziada values ek hi variable mei store karney chahrahe hai

In [4]:
#list arrar tuple index starts with 0

In [5]:
x=['qasim','mansoor']
print(x)
print(type(x))

['qasim', 'mansoor']
<class 'list'>


In [6]:
x=('qasim','mansoor')
print(x)
print(type(x))

('qasim', 'mansoor')
<class 'tuple'>


In [7]:
import numpy as np

In [9]:
x={'1':'qasim','2':'mansoor'} # key value pair jata hai
print(x)
print(type(x))

{'1': 'qasim', '2': 'mansoor'}
<class 'dict'>


In [11]:
data_1=np.array([1,2,3])
data_1

array([1, 2, 3])

In [26]:
data_1=np.random.randn(7)
data_1

array([ 1.38552257,  0.11495039, -0.12784692, -0.30908275,  0.06410034,
        0.40842812,  0.01161094])

In [19]:
data_1=np.random.randn(1,6)
data_1

array([[ 0.28051472,  0.7963808 ,  1.85933786, -0.29665051,  0.78098951,
         0.20351153]])

In [24]:
data_1=np.random.randn(0,6)#json format is mixed with dictionary
print(data_1)

[]


In [25]:
data_1.shape

(0, 6)

In [27]:
#for two dimension in numpy use randn(1,7)
#for one dimension in numpy use randn(7)

# Control Flow

In [30]:
data = {i : np.random.randn() for i in range(7)}
print(data) #creates a dictionary

{0: -0.4517312412908522, 1: -0.2880798565392658, 2: 0.4827619678531572, 3: -0.8480947246900157, 4: -0.5139237714199016, 5: 0.2640426693616832, 6: -0.11896236444144788}
